const quotes = [
  `“We cannot solve problems with the kind of thinking we employed when we came up with them.” — Albert Einstein`,
  `“Learn as if you will live forever, live like you will die tomorrow.” — Mahatma Gandhi`,
  `“Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too.” — Mark Twain`,
  `“When you give joy to other people, you get more joy in return. You should give a good thought to happiness that you can give out.” — Eleanor Roosevelt`,
  `“When you change your thoughts, remember to also change your world.” —Norman Vincent Peale`,
  `“It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest.” —Walter Anderson`,
  `“Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together.” —Diane McLaren`,
  `“Success is not final; failure is not fatal: It is the courage to continue that counts.” — Winston S. Churchill`,
  `“It is better to fail in originality than to succeed in imitation.” — Herman Melville`,
  `“The road to success and the road to failure are almost exactly the same.” — Colin R. Davis`,
  `“Success usually comes to those who are too busy looking for it.” — Henry David Thoreau`,
  `“Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.” —Dale Carnegie`,
  `“Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan 'Press On' has solved and always will solve the problems of the human race.” —Calvin Coolidge`,
  `“There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind.” —Mister Rogers`,
  `“Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable.” —John Wooden`,
  `“I never dreamed about success. I worked for it.” —Estée Lauder`,
  `“Success is getting what you want, happiness is wanting what you get.” —W. P. Kinsella`,
  `“The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.” — Winston Churchill`,
  `“Don’t let yesterday take up too much of today.” — Will Rogers`,
  `“You learn more from failure than from success. Don’t let it stop you. Failure builds character.” — Unknown`,
  `“If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.” — Steve Jobs`,
  `“Experience is a hard teacher because she gives the test first, the lesson afterwards.” —Vernon Sanders Law`,
  `“To know how much there is to know is the beginning of learning to live.” —Dorothy West`,
  `“[Goal setting](https://www.shopify.com/ph/blog/goal-setting) is the secret to a compelling future.” — Tony Robbins`,
  `“Women challenge the status quo because we are never it.” — Cindy Gallop`,
  `“We don’t just sit around and wait for other people. We just make, and we do.” — Arlan Hamilton`,
  `“Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness.” — Oprah Winfrey`,
  `“The strongest actions for a woman is to love herself, be herself and shine amongst those who never believed she could.” — Unknown`,
  `“Whenever you see a successful woman, look out for three men who are going out of their way to try to block her.” — Yulia Tymoshenko`,
  `“Some women choose to follow men, and some choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore.” — Lady Gaga`,
  `“The thing women have yet to learn is nobody gives you power. You just take it. ” — Roseanne Barr`,
  `“No woman wants to be in submission to a man who isn’t in submission to God!” — T D Jakes`,
  `“A witty woman is a treasure; a witty beauty is a power.” — George Meredith`,
  `“When a woman becomes her own best friend life is easier.” — Diane Von Furstenberg`,
  `“If you want something said, ask a man; if you want something done, ask a woman.” — Margaret Thatcher`,
  `“We need women at all levels, including the top, to change the dynamic, reshape the conversation, to make sure women’s voices are heard and heeded, not overlooked and ignored.” — Sheryl Sandberg`,
  `“It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent.” — Madeleine Albright`,
  `“Women must learn to play the game as men do.” — Eleanor Roosevelt`,
  `*“*I swear, by my life and my love of it, that I will never live for the sake of another man, nor ask another man to live for mine.” — Ayn Rand`,
  `“You've got to get up every morning with determination if you're going to go to bed with satisfaction.” — George Lorimer`,
  `“Education is the most powerful weapon which you can use to change the world.” — Nelson Mandela`,
  `“The most difficult thing is the decision to act, the rest is merely tenacity.” —Amelia Earhart`,
  `“Take the attitude of a student, never be too big to ask questions, never know too much to learn something new.” —Augustine Og Mandino`,
  `“Just one small positive thought in the morning can change your whole day.” — Dalai Lama`,
  `“Opportunities don't happen, you create them.” — Chris Grosser`,
  `“Love your family, work super hard, live your passion.” — Gary Vaynerchuk`,
  `“It is never too late to be what you might have been.” — George Eliot`,
  `“Don't let someone else's opinion of you become your reality” — Les Brown`,
  `“If you’re not positive energy, you’re negative energy.” — Mark Cuban`,
  `“I am not a product of my circumstances. I am a product of my decisions.” — Stephen R. Covey`,
];

export { quotes };